server:
  port: 9004

spring:
  application:
    name: requestService

  datasource:
    url: jdbc:mariadb://192.168.0.4:3306/co_option
    username: hammer
    password: hammer
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://121.111.164.3:3306/co_option
#    username: hanma
#    password: hanma
#    driver-class-name: org.mariadb.jdbc.Driver
    #mapper-locations: classpath:mapper/*.xml

mybatis:
  mapper-locations: classpath:mapper/*.xmlZ
  type-aliases-package: com.cooption.requestService.vo



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
