server:
  port: 9001

spring:
  application:
    name: userService

  datasource:

    url: jdbc:mariadb://121.111.164.3:3306/co_option
    username: hanma
    password: hanma
    driver-class-name: org.mariadb.jdbc.Driver
    mapper-locations: classpath:mapper/*.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cooption.userservice.vo

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
